import type { Metadata } from "next";
import { beau_rivage, geistSans, geistMono } from './fonts';
import "./globals.css";
import Header from "../components/layout/Header/header";
import { DataProvider } from './providers/DataProvider';

export const metadata: Metadata = {
  title: "SilverGuild",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${beau_rivage.variable} antialiased`}
      >
        <DataProvider>
          <div className="top-0">
            <Header />
          </div>
          <main>
            {children}
          </main>
        </DataProvider>
      </body>
    </html>
  );
}
