import type { Metadata } from "next";
import { beau_rivage, geistSans, geistMono } from './fonts';
import "./globals.css";
import Header from "../components/layout/Header/header";

export const metadata: Metadata = {
  title: "SilverGuild",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${beau_rivage.variable} antialiased`}
      >
        <div className="top-0">
          <Header />
        </div>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
